// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Device.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/cdi/types/helper.hpp"

#include "linglong/cdi/types/ContainerEdits.hpp"

namespace linglong {
namespace cdi {
namespace types {
using nlohmann::json;

struct Device {
std::optional<std::map<std::string, std::string>> annotations;
ContainerEdits containerEdits;
/**
* The name of the device
*/
std::string name;
};
}
}
}

// clang-format on
