// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     DeviceNode.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/cdi/types/helper.hpp"

namespace linglong {
namespace cdi {
namespace types {
using nlohmann::json;

struct DeviceNode {
std::optional<int64_t> gid;
std::optional<std::string> hostPath;
std::optional<int64_t> major;
std::optional<int64_t> minor;
std::string path;
std::optional<std::string> permissions;
std::optional<std::string> type;
std::optional<int64_t> uid;
};
}
}
}

// clang-format on
