// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Hook.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/cdi/types/helper.hpp"

namespace linglong {
namespace cdi {
namespace types {
using nlohmann::json;

struct Hook {
std::optional<std::vector<std::string>> args;
std::optional<std::vector<std::string>> env;
std::string hookName;
std::string path;
std::optional<int64_t> timeout;
};
}
}
}

// clang-format on
