// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     IntelRdt.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/cdi/types/helper.hpp"

namespace linglong {
namespace cdi {
namespace types {
using nlohmann::json;

struct IntelRdt {
std::optional<std::string> closID;
std::optional<bool> enableMonitoring;
std::optional<std::string> l3CacheSchema;
std::optional<std::string> memBWSchema;
std::optional<std::vector<std::string>> schemata;
};
}
}
}

// clang-format on
