// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     PackageInfo.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
using nlohmann::json;

struct PackageInfo {
std::string appID;
std::string arch;
std::optional<std::string> base;
std::string channel;
std::optional<std::string> description;
std::string kind;
std::string packageInfoModule;
std::string name;
std::optional<std::string> permissions;
std::optional<std::string> runtime;
/**
* Uncompressed package size in bytes
*/
int64_t size;
std::string version;
};
}
}
}
}

// clang-format on
