#!/bin/bash

# SPDX-FileCopyrightText: 2023 UnionTech Software Technology Co., Ltd.
#
# SPDX-License-Identifier: LGPL-3.0-or-later

LINGLONG_ROOT="@LINGLONG_ROOT@"

new_dirs=
while read -r install_path; do
	share_path=$install_path/entries/share
	case ":$XDG_DATA_DIRS:" in
	*":$share_path:"*) : ;;
	*":$share_path/:"*) : ;;
	*) new_dirs=${new_dirs:+${new_dirs}:}$share_path ;;
	esac
done < <(
	echo "${XDG_DATA_HOME:-"$HOME/.local/share"}/linglong"
	echo "${LINGLONG_ROOT}"
)

XDG_DATA_DIRS="${new_dirs:+${new_dirs}:}${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
echo "XDG_DATA_DIRS=\"$XDG_DATA_DIRS\""
