#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2023-2025 UnionTech Software Technology Co., Ltd.
#
# SPDX-License-Identifier: LGPL-3.0-or-later

# shellcheck shell=sh

# Profile.d script for linglong/linyaps
# This script sources the host environment generator and prints the
# modified XDG_DATA_DIRS and PATH variables for user sessions.

source_script="@CMAKE_INSTALL_PREFIX@/lib/linglong/generate-xdg-data-dirs.sh"

# Source the script if available
[ -r "${source_script}" ] && . "${source_script}"

# !!!systemd requires environment variables to be printed to standard output!!!
# https://www.freedesktop.org/software/systemd/man/latest/systemd.environment-generator.html
[ -n "${XDG_DATA_DIRS}" ] && echo "XDG_DATA_DIRS=${XDG_DATA_DIRS}"
[ -n "${PATH}" ] && echo "PATH=${PATH}"
