// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     AllowPath.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* Allow the application to access the directory
*/

using nlohmann::json;

/**
* Allow the application to access the directory
*/
struct AllowPath {
/**
* Relative to the home directory
*/
std::string path;
/**
* Access permissions. Default is rw, optional ro
*/
std::optional<std::string> permissions;
};
}
}
}
}

// clang-format on
