// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     ApplicationSetting.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

#include "linglong/api/types/v1/AllowPath.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* User settings for the application
*/

using nlohmann::json;

/**
* User settings for the application
*/
struct ApplicationSetting {
std::optional<std::vector<AllowPath>> allowPaths;
};
}
}
}
}

// clang-format on
