// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     ApplicationConfigurationPermissionsBind.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* items of container
*/

using nlohmann::json;

/**
* items of container
*/
struct ApplicationConfigurationPermissionsBind {
/**
* mount source file to the container
*/
std::string destination;
/**
* source file of host
*/
std::string source;
};
}
}
}
}

// clang-format on
