// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     BuilderProjectPackage.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* package of build file
*/

using nlohmann::json;

/**
* package of build file
*/
struct BuilderProjectPackage {
/**
* architecture of package
*/
std::optional<std::string> architecture;
/**
* channel of package
*/
std::optional<std::string> channel;
/**
* description of package
*/
std::string description;
/**
* Predefined environment variables when the extension is applied
*/
std::optional<std::map<std::string, std::string>> env;
/**
* extension of whom
*/
std::optional<std::string> extensionOf;
/**
* id of package
*/
std::string id;
/**
* kind of package
*/
std::string kind;
/**
* extra ld search path
*/
std::optional<std::vector<std::string>> libs;
/**
* name of package
*/
std::string name;
/**
* version of package
*/
std::string version;
};
}
}
}
}

// clang-format on
