// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     CdiDeviceEntry.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

#include "linglong/api/types/v1/CdiSpec.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
using nlohmann::json;

struct CdiDeviceEntry {
/**
* CDI device kind which uniquely identifies the device vendor
*/
std::string kind;
/**
* CDI device name
*/
std::string name;
/**
* CDI device spec
*/
CdiSpec spec;
};
}
}
}
}

// clang-format on
