// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     CdiSpec.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* CDI device spec
*/

using nlohmann::json;

/**
* CDI device spec
*/
struct CdiSpec {
/**
* CDI device spec checksum
*/
std::string checksum;
/**
* CDI device spec path
*/
std::string path;
};
}
}
}
}

// clang-format on
