// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     CliContainer.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* this is the output result of ll-cli ps --json
*/

using nlohmann::json;

/**
* this is the output result of ll-cli ps --json
*/
struct CliContainer {
/**
* id of container
*/
std::string id;
/**
* package of container
*/
std::string package;
/**
* pid of container
*/
int64_t pid;
};
}
}
}
}

// clang-format on
