// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     ContainerProcessStateInfo.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* information about process which in container that start by ll-cli, all content
* will write to /run/linglong/UID/PID
*/

using nlohmann::json;

/**
* information about process which in container that start by ll-cli, all content
* will write to /run/linglong/UID/PID
*/
struct ContainerProcessStateInfo {
std::string app;
std::string base;
std::string containerID;
/**
* extensions of container
*/
std::optional<std::vector<std::string>> extensions;
std::optional<std::string> runtime;
};
}
}
}
}

// clang-format on
