// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     InspectResult.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* the result of inspecting a container
*/

using nlohmann::json;

/**
* the result of inspecting a container
*/
struct InspectResult {
/**
* appID of container
*/
std::optional<std::string> appID;
};
}
}
}
}

// clang-format on
