// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     InteractionRequest.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* structured message which inspired by freedesktop Notification Spec.
* refer:
* https://specifications.freedesktop.org/notification-spec/latest/protocol.html#id-1.10.3.3.4
*/

using nlohmann::json;

/**
* structured message which inspired by freedesktop Notification Spec.
* refer:
* https://specifications.freedesktop.org/notification-spec/latest/protocol.html#id-1.10.3.3.4
*/
struct InteractionRequest {
std::optional<std::vector<std::string>> actions;
std::string appName;
std::optional<std::string> body;
std::string summary;
int64_t timeout;
};
}
}
}
}

// clang-format on
