// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     InteractionReply.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* message from user reply
*/

using nlohmann::json;

/**
* message from user reply
*/
struct InteractionReply {
/**
* choice which in requested actions
*/
std::optional<std::string> action;
};
}
}
}
}

// clang-format on
