// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     InteractionMessageType.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* To identify what message to print during interaction.
*/

using nlohmann::json;

/**
* To identify what message to print during interaction.
*/
enum class InteractionMessageType : int { Downgrade, Install, Uninstall, Unknown, Upgrade };
}
}
}
}

// clang-format on
