// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     LlCLIFilesystemEntry.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* filesystem entry used by ll-cli configuration
*/

using nlohmann::json;

/**
* filesystem entry used by ll-cli configuration
*/
struct LlCLIFilesystemEntry {
/**
* source path on host
*/
std::string host;
/**
* mount mode, either ro or rw
*/
std::optional<std::string> mode;
/**
* whether this mount should persist in sandbox storage
*/
std::optional<bool> persist;
/**
* mount target path inside container
*/
std::string target;
};
}
}
}
}

// clang-format on
