// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     LlCLICommandConfig.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

#include "linglong/api/types/v1/LlCLIFilesystemEntry.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* per-command overrides for ll-cli configuration
*/

using nlohmann::json;

/**
* per-command overrides for ll-cli configuration
*/
struct LlCLICommandConfig {
/**
* arguments prepended before command
*/
std::optional<std::vector<std::string>> argsPrefix;
/**
* arguments appended after command
*/
std::optional<std::vector<std::string>> argsSuffix;
/**
* working directory for command
*/
std::optional<std::string> cwd;
/**
* override entrypoint for command
*/
std::optional<std::string> entrypoint;
/**
* environment variables applied to command
*/
std::optional<std::map<std::string, std::string>> env;
/**
* filesystem entries applied to command
*/
std::optional<std::vector<LlCLIFilesystemEntry>> filesystem;
};
}
}
}
}

// clang-format on
