// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     PackageManager1PackageExportTaskResult.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* package manager export uab task result
*
* package manager task result
*
* this is common error result of ll-cli command --json
*/

using nlohmann::json;

/**
* package manager export uab task result
*
* package manager task result
*
* this is common error result of ll-cli command --json
*/
struct PackageManager1PackageExportTaskResult {
/**
* export uab path of installed app
*/
std::optional<std::string> exportPath;
/**
* task dbus object path of package manager install
*/
std::optional<std::string> taskObjectPath;
/**
* We do not use DBus error. We return an error code instead. Non-zero code indicated errors
* occurs and message should be displayed to user.
*/
int64_t code;
/**
* Human readable result message.
*/
std::string message;
/**
* error type, to indicate client what should be done.
*/
std::string type;
};
}
}
}
}

// clang-format on
