// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     PackageManager1SearchParameters.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* package manager search parameters
*/

using nlohmann::json;

/**
* package manager search parameters
*/
struct PackageManager1SearchParameters {
/**
* id of package manager search
*/
std::string id;
/**
* search packages in specified repo.
*/
std::optional<std::string> repo;
};
}
}
}
}

// clang-format on
