// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     PackageTaskMessage.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

#include "linglong/api/types/v1/CommonResult.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
enum class State : int;
enum class SubState : int;
}
}
}
}

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* all message which should report from package manager to frontend
*/

using nlohmann::json;

/**
* all message which should report from package manager to frontend
*/
struct PackageTaskMessage {
/**
* Human readable message to report additional message
*/
std::string message;
/**
* present total progress
*/
double percentage;
std::optional<CommonResult> result;
/**
* main state of current task,
*/
State state;
/**
* subState of current task,
*/
SubState subState;
};
}
}
}
}

// clang-format on
