// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     RepositoryCacheLayersItem.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

#include "linglong/api/types/v1/PackageInfoV2.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* stores the full module name with repo name and the corresponding ostree commit
*/

using nlohmann::json;

/**
* stores the full module name with repo name and the corresponding ostree commit
*/
struct RepositoryCacheLayersItem {
/**
* ostree commit hash
*/
std::string commit;
/**
* deleted mark
*/
std::optional<bool> deleted;
PackageInfoV2 info;
/**
* which repo is this app belongs to
*/
std::string repo;
};
}
}
}
}

// clang-format on
