// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     RunContextConfig.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

#include "linglong/api/types/v1/CdiDeviceEntry.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
using nlohmann::json;

struct RunContextConfig {
std::optional<std::string> app;
std::optional<std::string> base;
std::optional<std::vector<CdiDeviceEntry>> cdiDevices;
std::optional<std::map<std::string, std::vector<std::string>>> extensions;
std::optional<std::string> overlayfs;
std::optional<std::string> runtime;
std::optional<std::string> timezone;
std::string version;
};
}
}
}
}

// clang-format on
