// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     RuntimeConfigure.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

#include "linglong/api/types/v1/ExtensionDefine.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
using nlohmann::json;

struct RuntimeConfigure {
std::optional<std::map<std::string, std::string>> env;
/**
* external extension definitions to extend the component
*/
std::optional<std::map<std::string, std::vector<ExtensionDefine>>> extDefs;
};
}
}
}
}

// clang-format on
