// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     SubState.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* subState of current task,
*/

using nlohmann::json;

/**
* subState of current task,
*/
enum class SubState : int { Done, InstallApplication, InstallBase, InstallRuntime, PostAction, PreAction, Uninstall, Unknown };
}
}
}
}

// clang-format on
