// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     TaskState.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
enum class State : int;
}
}
}
}

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* complete state information of a task
*/

using nlohmann::json;

/**
* complete state information of a task
*/
struct TaskState {
std::string message;
double progress;
State state;
};
}
}
}
}

// clang-format on
