// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     UpgradeListResult.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* this is upgrade list result of ll-cli upgrade --json
*/

using nlohmann::json;

/**
* this is upgrade list result of ll-cli upgrade --json
*/
struct UpgradeListResult {
/**
* id of package.
*/
std::string id;
/**
* version of latest version in remote repo.
*/
std::string newVersion;
/**
* version of current installed.
*/
std::string oldVersion;
};
}
}
}
}

// clang-format on
