// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     XdgDirectoryPermission.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
using nlohmann::json;

struct XdgDirectoryPermission {
/**
* whether the xdg dir is allowed
*/
bool allowed;
/**
* type of xdg dir, could be one of [Desktop, Downloads, Documents, Music, Pictures, Videos]
*/
std::string dirType;
};
}
}
}
}

// clang-format on
