name: Build and test cpp library

on: [pull_request]

jobs:
  build-cpp:
    env:
      CTEST_OUTPUT_ON_FAILURE: '1'
    permissions:
      checks: write
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++
          - clang++
        qt-version:
          - '5'
          - '6'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ matrix.compiler }}-qt${{ matrix.qt-version }}
    - name: Install dependencies
      run: |
        sudo apt update &&
        sudo apt-get install -y \
          clang clang-tidy ninja-build \
          libgtest-dev qtbase5-dev qt6-base-dev
    - name: Setup build directory with ${{ matrix.compiler }} and qt${{ matrix.qt-version }}
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        if [ ${{ matrix.compiler }} == "clang++" ]; then
          export CMAKE_CLANG_TIDY_ARG="-DCMAKE_CXX_CLANG_TIDY=clang-tidy;--export-fixes=clang-tidy-fixes.yaml"
        fi
        cmake \
          -B build \
          -DCMAKE_GENERATOR="Ninja Multi-Config" \
          -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror" \
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
          -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" \
          ${CMAKE_CLANG_TIDY_ARG} \
          -DQSERIALIZER_QT_VERSION_MAJOR=${{ matrix.qt-version }}
    - name: Try to build with Debug config to generate clang-tidy-fixes.yaml
      # NOTE:
      # Only generate comments from clang++ and qt6
      # to avoid duplicate comments.
      if: matrix.compiler == 'clang++' && matrix.qt-version == '6'
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake --build build --config Debug -j
      continue-on-error: true
    - name: Generate PR comments with clang-tidy
      if: matrix.compiler == 'clang++' && matrix.qt-version == '6'
      uses: platisd/clang-tidy-pr-comments@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        clang_tidy_fixes: build/clang-tidy-fixes.yaml
        request_changes: false
        suggestions_per_comment: 10
    - name: Build and test with ${{ matrix.compiler }} and qt${{ matrix.qt-version }}
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake --build build --config Debug -j &&
        cmake --build build -t test --config Debug &&
        cmake --build build --config Release -j &&
        cmake --build build -t test --config Release &&
        cmake --build build --config RelWithDebInfo -j &&
        cmake --build build -t test --config RelWithDebInfo
