#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 UnionTech Software Technology Co., Ltd.
#
# SPDX-License-Identifier: LGPL-3.0-or-later

exec @CMAKE_INSTALL_FULL_LIBEXECDIR@/linglong/ll-dialog --mode=permission
