#!/bin/bash

# SPDX-FileCopyrightText: 2023 UnionTech Software Technology Co., Ltd.
#
# SPDX-License-Identifier: LGPL-3.0-or-later

ll-cli list --type=all | tail -n +2 | awk '{print  $1}' | xargs -I {} sh -c "ll-cli upgrade {} || true; sleep 5"
