// Thish file is generated by /tools/run-quicktype.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Generators.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <nlohmann/json.hpp>
#include "linglong/builder/config/helper.hpp"

#include "linglong/builder/config/Config.hpp"

namespace linglong {
namespace builder {
namespace config {
void from_json(const json & j, Config & x);
void to_json(json & j, const Config & x);

inline void from_json(const json & j, Config& x) {
x.remoteRepoEndpoint = j.at("remoteRepoEndpoint").get<std::string>();
x.remoteRepoName = j.at("remoteRepoName").get<std::string>();
}

inline void to_json(json & j, const Config & x) {
j = json::object();
j["remoteRepoEndpoint"] = x.remoteRepoEndpoint;
j["remoteRepoName"] = x.remoteRepoName;
}
}
}
}

// clang-format on
