#!/bin/env bash

# This script should be called by systemd in the ExecStartPre field of
# org.deepin.linglong.PackageManager.service to create LINGLONG_ROOT dir.

if [[ $(id -u) -ne 0 ]]; then
    echo "This script must be run as root."
    exit 255
fi

LINGLONG_ROOT=${LINGLONG_ROOT:-/var/lib/linglong}

mkdir -p ${LINGLONG_ROOT}
mkdir -p /var/log/linglong

chown linglong:linglong ${LINGLONG_ROOT}
chown linglong:linglong /var/log/linglong
chmod o+w /var/log/linglong # FIXME: remove this later.
