// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     BuilderConfig.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* Configuration file for ll-builder.
*/

using nlohmann::json;

/**
* Configuration file for ll-builder.
*/
struct BuilderConfig {
/**
* arch of builder config
*/
std::optional<std::string> arch;
/**
* cache of builder config
*/
std::optional<std::string> cache;
/**
* use offline mode when build
*/
std::optional<bool> offline;
/**
* repo of builder config
*/
std::string repo;
/**
* skip commit output when build
*/
std::optional<bool> skipCommitOutput;
/**
* skip fetch source when build
*/
std::optional<bool> skipFetchSource;
/**
* skip pull depend when build
*/
std::optional<bool> skipPullDepend;
/**
* skip run container when build
*/
std::optional<bool> skipRunContainer;
/**
* version of builder config
*/
int64_t version;
};
}
}
}
}

// clang-format on
