// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     BuilderProjectPackage.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
using nlohmann::json;

struct BuilderProjectPackage {
std::optional<std::string> architecture;
std::optional<std::string> channel;
std::string description;
std::string id;
std::string kind;
std::string name;
std::string version;
};
}
}
}
}

// clang-format on
