// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     LayerInfo.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* Meta infomation on the head of layer file.
*/

using nlohmann::json;

/**
* Meta infomation on the head of layer file.
*/
struct LayerInfo {
nlohmann::json info;
std::string version;
};
}
}
}
}

// clang-format on
