// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     PackageManager1GetRepoInfoResultRepoInfo.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* result of package manager get repo info
*/

using nlohmann::json;

/**
* result of package manager get repo info
*/
struct PackageManager1GetRepoInfoResultRepoInfo {
/**
* default repo of package manager get repo info
*/
std::string defaultRepo;
/**
* repos of package manager get repo info
*/
std::map<std::string, std::string> repos;
};
}
}
}
}

// clang-format on
