// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     PackageManager1Package.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* package manager of linglong
*/

using nlohmann::json;

/**
* package manager of linglong
*/
struct PackageManager1Package {
/**
* channel of package manager
*/
std::optional<std::string> channel;
/**
* id of package manager
*/
std::string id;
/**
* module of package manager
*/
std::optional<std::string> packageManager1PackageModule;
/**
* version of package manager
*/
std::optional<std::string> version;
};
}
}
}
}

// clang-format on
