// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     UabInfo.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v1/helper.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v1 {
/**
* additional information for exporting uab
*/

using nlohmann::json;

/**
* additional information for exporting uab
*/
struct UabInfo {
/**
* path to directory which contains extra files used by loader to start container
*/
std::optional<std::string> extra;
/**
* path to the execution entry of uab
*/
std::optional<std::string> loader;
};
}
}
}
}

// clang-format on
