debian/sysctl.d/linglong.conf usr/lib/sysctl.d/
etc/X11/Xsession.d/21linglong
etc/profile.d/linglong.sh
usr/bin/ll-cli
usr/bin/llpkg
usr/lib/linglong/*
usr/lib/systemd/system-environment-generators/61-linglong
usr/lib/systemd/user-generators/linglong-user-systemd-generator
usr/lib/systemd/system/org.deepin.linglong.PackageManager.service lib/systemd/system/
usr/lib/systemd/user/linglong-session-helper.service
usr/lib/sysusers.d/linglong.conf
usr/lib/tmpfiles.d/linglong.conf
usr/libexec/linglong/ll-package-manager
usr/libexec/linglong/ll-session-helper
usr/libexec/linglong/ld-cache-generator
usr/libexec/linglong/font-cache-generator
usr/libexec/linglong/ll-dialog
usr/libexec/linglong/dialog/99-linglong-permission
usr/share/bash-completion/completions/ll-cli
usr/share/zsh/vendor-completions/_ll-cli
usr/share/dbus-1/system-services/org.deepin.linglong.PackageManager1.service
usr/share/dbus-1/system.d/org.deepin.linglong.PackageManager1.conf
usr/share/linglong/config.yaml
usr/share/locale
usr/share/mime/packages/vnd.linyaps.uab.xml
usr/share/polkit-1/actions/org.deepin.linglong.PackageManager1.policy
