#!/bin/bash

LINGLONG_ROOT="/var/lib/linglong"
VERSION=""

if [ -f /etc/os-release ]
then
        VERSION=$(sed -ne '/^VERSION_ID=.*$/P' /etc/os-release | awk -F = '{print $2}' | sed -e 's/"//g')
        if [ $(echo "${VERSION} >= 20 && ${VERSION} < 23" | bc) = 1 ]
        then
                LINGLONG_ROOT="/data/linglong"
        elif [ $(echo "${VERSION} >= 23" | bc) = 1 ]
        then
                LINGLONG_ROOT="/persistent/linglong"
        fi
fi

if [ ! -d ${LINGLONG_ROOT}/repo ]
then
	mkdir -p ${LINGLONG_ROOT}/layers
	ostree --repo=${LINGLONG_ROOT}/repo init --mode=bare-user-only
	ostree --repo=${LINGLONG_ROOT}/repo remote add --no-gpg-verify repo  https://linglong-api-dev.deepin.com/ostree/
	chmod -R 0755 $(dirname ${LINGLONG_ROOT})
else
	echo "Directory is already exists."
fi

#copy config.json to LINGLONG_ROOT
if [ ! -f ${LINGLONG_ROOT}/config.json ]
then
	cp /usr/share/linglong/config.json ${LINGLONG_ROOT}/config.json
fi

#daemon-reload for /usr/lib/systemd/user-environment-generators/61-linglong
if [ -f /usr/lib/systemd/user-environment-generators/61-linglong ]
then
	systemctl daemon-reload
fi

if [ -d /usr/share/permission/policy/linglong ]
then
	rm -rf /usr/share/permission/policy/linglong
fi

if [ `grep -cw "deepin-linglong" /etc/passwd` -gt '0' ]
then
	usermod -s /sbin/nologin deepin-linglong
        if ! `groups deepin-linglong |grep -qw "users"`
        then
                gpasswd -a deepin-linglong users
        fi
else
        useradd -s /sbin/nologin deepin-linglong
        gpasswd -a deepin-linglong users
fi
chown deepin-linglong:users /usr/bin/ll-system-helper