// Thish file is generated by /tools/codegen
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Apparmor.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "ocppi/runtime/features/types/helper.hpp"

namespace ocppi {
namespace runtime {
namespace features {
namespace types {
using nlohmann::json;

struct Apparmor {
std::optional<bool> enabled;
};
}
}
}
}

// clang-format on
