// Thish file is generated by /tools/codegen
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Image.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "ocppi/runtime/config/types/helper.hpp"

namespace ocppi {
namespace runtime {
namespace config {
namespace types {
enum class RootImageFormat : int;
}
}
}
}

namespace ocppi {
namespace runtime {
namespace config {
namespace types {
/**
* root image config used by VM-based containers
*/

using nlohmann::json;

/**
* root image config used by VM-based containers
*/
struct Image {
RootImageFormat format;
std::string path;
};
}
}
}
}

// clang-format on
