// Thish file is generated by /tools/codegen
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Seccomp.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "ocppi/runtime/config/types/helper.hpp"

#include "ocppi/runtime/config/types/Syscall.hpp"

namespace ocppi {
namespace runtime {
namespace config {
namespace types {
enum class SeccompArch : int;
enum class SeccompAction : int;
enum class SeccompFlag : int;
}
}
}
}

namespace ocppi {
namespace runtime {
namespace config {
namespace types {
using nlohmann::json;

struct Seccomp {
std::optional<std::vector<SeccompArch>> architectures;
SeccompAction defaultAction;
std::optional<int64_t> defaultErrnoRet;
std::optional<std::vector<SeccompFlag>> flags;
std::optional<std::string> listenerMetadata;
std::optional<std::string> listenerPath;
std::optional<std::vector<Syscall>> syscalls;
};
}
}
}
}

// clang-format on
