// Thish file is generated by /tools/codegen
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     User.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "ocppi/runtime/config/types/helper.hpp"

namespace ocppi {
namespace runtime {
namespace config {
namespace types {
using nlohmann::json;

struct User {
std::optional<std::vector<int64_t>> additionalGids;
std::optional<int64_t> gid;
std::optional<int64_t> uid;
std::optional<int64_t> umask;
std::optional<std::string> username;
};
}
}
}
}

// clang-format on
