// Thish file is generated by /tools/codegen
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     WindowsResources.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "ocppi/runtime/config/types/helper.hpp"

#include "ocppi/runtime/config/types/FluffyCPU.hpp"
#include "ocppi/runtime/config/types/FluffyMemory.hpp"
#include "ocppi/runtime/config/types/Storage.hpp"

namespace ocppi {
namespace runtime {
namespace config {
namespace types {
using nlohmann::json;

struct WindowsResources {
std::optional<FluffyCPU> cpu;
std::optional<FluffyMemory> memory;
std::optional<Storage> storage;
};
}
}
}
}

// clang-format on
