// Thish file is generated by /tools/codegen
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     ZosDevice.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "ocppi/runtime/config/types/helper.hpp"

namespace ocppi {
namespace runtime {
namespace config {
namespace types {
using nlohmann::json;

struct ZosDevice {
std::optional<int64_t> fileMode;
std::optional<int64_t> gid;
int64_t major;
int64_t minor;
std::string path;
std::string type;
std::optional<int64_t> uid;
};
}
}
}
}

// clang-format on
