// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     ApplicationConfigurationPermissions.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v0/helper.hpp"

#include "linglong/api/types/v0/ApplicationConfigurationPermissionsBind.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v0 {
using nlohmann::json;

struct ApplicationConfigurationPermissions {
std::optional<std::vector<ApplicationConfigurationPermissionsBind>> binds;
};
}
}
}
}

// clang-format on
