// This file is generated by tools/codegen.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     LinglongAPIV0.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include "linglong/api/types/v0/helper.hpp"

#include "linglong/api/types/v0/ApplicationConfigurationPermissions.hpp"
#include "linglong/api/types/v0/PackageInfo.hpp"

namespace linglong {
namespace api {
namespace types {
namespace v0 {
/**
* Types used as v0 API of linglong D-Bus service, configuration files and CLI output. These
* types all should be removed later. The top level type is a place holder to make quicktype
* work.
*/

using nlohmann::json;

/**
* Types used as v0 API of linglong D-Bus service, configuration files and CLI output. These
* types all should be removed later. The top level type is a place holder to make quicktype
* work.
*/
struct LinglongAPIV0 {
std::optional<ApplicationConfigurationPermissions> applicationConfigurationPermissions;
std::optional<PackageInfo> packageInfo;
};
}
}
}
}

// clang-format on
