#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 UnionTech Software Technology Co., Ltd.
#
# SPDX-License-Identifier: LGPL-3.0-or-later

echo "This is a placeholder file for using builtin oci configuration generator.
If you want to customize the behavior of current generator,
you could replace this file with a same name executable file." 1>&2

exit 255
