#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 UnionTech Software Technology Co., Ltd.
#
# SPDX-License-Identifier: LGPL-3.0-or-later

# LINGLONG_BUILTIN_GENERATOR

# if you want to use custom generator, please add your implementation here and remove above "LINGLONG_BUILTIN_GENERATOR" comment
