#!/bin/bash

LINGLONG_ROOT="/var/lib/linglong"
VERSION=""

if [ -f /etc/os-release ]
then
        VERSION=$(sed -ne '/^VERSION_ID=.*$/P' /etc/os-release | awk -F = '{print $2}' | sed -e 's/"//g')
        if [ $(echo "${VERSION} >= 20 && ${VERSION} < 23" | bc) = 1 ]
        then
                LINGLONG_ROOT="/data/linglong"
        elif [ $(echo "${VERSION} >= 23" | bc) = 1 ]
        then
                LINGLONG_ROOT="/persistent/linglong"
        fi
fi

new_dirs=
while read -r install_path
do
    share_path=$install_path/entries/share
    case ":$XDG_DATA_DIRS:" in
        *":$share_path:"*) :;;
        *":$share_path/:"*) :;;
        *) new_dirs=${new_dirs:+${new_dirs}:}$share_path;;
    esac
done < <(echo "${XDG_DATA_HOME:-"$HOME/.local/share"}/linglong"; echo "${LINGLONG_ROOT}")

XDG_DATA_DIRS="${new_dirs:+${new_dirs}:}${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
echo "XDG_DATA_DIRS=$XDG_DATA_DIRS"
echo LINGLONG_ROOT=${LINGLONG_ROOT}