#include "oci.h"

QSERIALIZER_IMPL(Root);
QSERIALIZER_IMPL(Namespace);
QSERIALIZER_IMPL(IdMap);
QSERIALIZER_IMPL(Linux);
QSERIALIZER_IMPL(Process);
QSERIALIZER_IMPL(Mount);
QSERIALIZER_IMPL(Hook);
QSERIALIZER_IMPL(Hooks);
QSERIALIZER_IMPL(AnnotationsOverlayfsRootfs);
QSERIALIZER_IMPL(AnnotationsNativeRootfs);
QSERIALIZER_IMPL(DBusProxy);
QSERIALIZER_IMPL(Annotations);
QSERIALIZER_IMPL(Runtime);
