// Thish file is generated by /tools/run-quicktype.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Generators.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <nlohmann/json.hpp>
#include "linglong/repo/config/helper.hpp"

#include "linglong/repo/config/ConfigV1.hpp"

namespace linglong {
namespace repo {
namespace config {
void from_json(const json & j, ConfigV1 & x);
void to_json(json & j, const ConfigV1 & x);

inline void from_json(const json & j, ConfigV1& x) {
x.defaultRepo = j.at("defaultRepo").get<std::string>();
x.repos = j.at("repos").get<std::map<std::string, std::string>>();
x.version = j.at("version").get<int64_t>();
}

inline void to_json(json & j, const ConfigV1 & x) {
j = json::object();
j["defaultRepo"] = x.defaultRepo;
j["repos"] = x.repos;
j["version"] = x.version;
}
}
}
}

// clang-format on
