# SPDX-FileCopyrightText: 2023 UnionTech Software Technology Co., Ltd.
#
# SPDX-License-Identifier: LGPL-3.0-or-later

variables:
  build_dir: |
  conf_args: |
  extra_args: |
  destdir: |
  jobs: -j${JOBS}
  c_flags: |
  cxx_flags: |
  ld_flags: |  

build:
  kind: manual
  manual :
    configure: |
    build: |
    install: |

environment:
  CFLAGS: |
    -isystem/runtime/include -g -O2 -fstack-protector-strong -Wformat -Werror=format-security ${c_flags}
  CXXFLAGS: |
    -isystem/runtime/include -g -O2 -fstack-protector-strong -Wformat -Werror=format-security ${c_flags}
  LDFLAGS: |
    -Wl,-z,relro ${ld_flags}
