// Thish file is generated by /tools/run-quicktype.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Generators.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <nlohmann/json.hpp>
#include "linglong/package/layer/helper.hpp"

#include "linglong/package/layer/LayerInfo.hpp"

namespace linglong {
namespace package {
namespace layer {
void from_json(const json & j, LayerInfo & x);
void to_json(json & j, const LayerInfo & x);

inline void from_json(const json & j, LayerInfo& x) {
x.info = j.at("info").get<std::map<std::string, nlohmann::json>>();
x.version = j.at("version").get<std::string>();
}

inline void to_json(json & j, const LayerInfo & x) {
j = json::object();
j["info"] = x.info;
j["version"] = x.version;
}
}
}
}

// clang-format on
