// Thish file is generated by /tools/run-quicktype.sh
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     LayerInfo.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <nlohmann/json.hpp>
#include "linglong/package/layer/helper.hpp"

namespace linglong {
namespace package {
namespace layer {
/**
* Configuration file for layer.
*/

using nlohmann::json;

/**
* Configuration file for layer.
*/
struct LayerInfo {
std::map<std::string, nlohmann::json> info;
std::string version;
};
}
}
}

// clang-format on
